allprojects {
    repositories {
        mavenCentral()
        jcenter()
        google()
    }
}

buildscript {
    repositories {
        mavenCentral()
        jcenter()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.3'
    }
}

apply plugin: 'com.android.application'

dependencies {
    implementation project(':AndroidME')
    implementation fileTree(include: '*.jar', dir: 'libs')
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.google.android.gms:play-services-games:17.0.0'
    implementation 'com.google.android.play:core:1.9.1'
    // some things are broken when moving to org.apache.httpcomponents:http 4.2+
    implementation 'org.apache.httpcomponents:httpcore:4.1.2'
    implementation 'org.apache.httpcomponents:httpmime:4.1.2'
    implementation 'androidx.annotation:annotation:1.2.0'
}

android {
    compileOptions.encoding = 'cp1252'
    compileSdkVersion 28
    buildToolsVersion '28.0.3'
    // this to to avoid error from httpcore-4.1.2.jar and httpcore-4.1.2.jar having the same file
    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
    }
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['../src', 'src', '../sharedUI/src_mini_game_ui', '../sharedUI/src_mapstore_lobby']
            resources.srcDirs = ['../src', '../sharedUI/res_mini_game_ui', '../sharedUI/res_mapstore_lobby']
            res.srcDirs = ['res', '../sharedUI/img_mini_game_ui', '../sharedUI/img_mapstore_lobby']
            assets.srcDirs = ['assets']
        }
    }
    // this is to avoid the @TargetApi missing on methods giving errors.
    lintOptions {
        abortOnError false
    }
    defaultConfig {
        minSdkVersion 4
    }
}

// same as ant tasks "setup.android"
task copyAssets(type: Copy) {
    from('../swingUI/game/Domination') {
        include 'maps/**'
        include 'help/**'
    }
    from('../src/META-INF') {
        include 'services/**'
    }
    from '../gpl.txt'
    from '../ChangeLog.txt'
    into 'assets'
}
project.preBuild.dependsOn(copyAssets)

